//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIKEDPOST
    {
        public int ID { get; set; }
        public int USERID { get; set; }
        public int POSTID { get; set; }
    
        public virtual POST POST { get; set; }
        public virtual USER USER { get; set; }
    }
}
