//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOCIALMEDIA_DBEntities2 : DbContext
    {
        public SOCIALMEDIA_DBEntities2()
            : base("name=SOCIALMEDIA_DBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENTS> COMMENTS { get; set; }
        public virtual DbSet<FOLLOWINGS> FOLLOWINGS { get; set; }
        public virtual DbSet<LIKEDPOSTS> LIKEDPOSTS { get; set; }
        public virtual DbSet<POSTS> POSTS { get; set; }
        public virtual DbSet<REPLIES> REPLIES { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
