//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOCIALMEDIA_DBEntities : DbContext
    {
        public SOCIALMEDIA_DBEntities()
            : base("name=SOCIALMEDIA_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENT> COMMENTS { get; set; }
        public virtual DbSet<FOLLOWING> FOLLOWINGS { get; set; }
        public virtual DbSet<POST> POSTS { get; set; }
        public virtual DbSet<REPLY> REPLIES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<LIKEDPOST> LIKEDPOSTS { get; set; }
    }
}
