//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMediaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.COMMENTS = new HashSet<COMMENT>();
            this.FOLLOWINGS = new HashSet<FOLLOWING>();
            this.FOLLOWINGS1 = new HashSet<FOLLOWING>();
            this.POSTS = new HashSet<POST>();
            this.REPLIES = new HashSet<REPLY>();
            this.LIKEDPOSTS = new HashSet<LIKEDPOST>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DISPLAYPICTURE { get; set; }
        public string BG { get; set; }
        public System.DateTime DOB { get; set; }
        public bool GENDER { get; set; }
        public string BIO { get; set; }
        public string EMAIL { get; set; }
        public string FRstatus { get; set; }
    
        public virtual ICollection<COMMENT> COMMENTS { get; set; }
        public virtual ICollection<FOLLOWING> FOLLOWINGS { get; set; }
        public virtual ICollection<FOLLOWING> FOLLOWINGS1 { get; set; }
        public virtual ICollection<POST> POSTS { get; set; }
        public virtual ICollection<REPLY> REPLIES { get; set; }
        public virtual ICollection<LIKEDPOST> LIKEDPOSTS { get; set; }
    }
}
